version: 2
jobs:
  deploy:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - run: 
          name: Deploy Master Branch
          command: |
            sudo apt-get update
            sudo apt-get -qq install git-ftp
            echo "Deploying project ..."
            echo $(git status)
            git config git-ftp.user ${FTP_USER}
            git config git-ftp.url ${FTP_URL}
            git config git-ftp.password "${FTP_PWD}"
            git ftp push -u "${FTP_USER}" -p "${FTP_PWD}" --remote-root ${FTP_LOCATION} ${FTP_URL}
 
workflows:
  version: 2
  just-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master